/**
 * Parent artifacts API — generates a session/weekly/monthly summary as
 * Markdown (PDF-ready) and returns a share token. Token-based view is
 * intentionally opaque so parents can open the link without a Supabase
 * account, but the content cannot be guessed.
 *
 * GET            → list user's recent artifacts
 * GET ?token=... → public artifact view (no auth required)
 * POST { kind: 'session_summary' | 'weekly_digest' | 'monthly_report' }
 *                → generate a fresh artifact, return body + share token
 */

import { NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase';
import { randomBytes } from 'crypto';

function shareToken(): string {
  return randomBytes(16).toString('base64url');
}

export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const token = url.searchParams.get('token');
    const supabase: any = await createServerClient();

    if (token) {
      // Public read by token — no auth needed (the token is the auth).
      const { data } = await supabase
        .from('parent_artifacts')
        .select('artifact_kind, title, body_md, language, generated_at, expires_at')
        .eq('share_token', token)
        .maybeSingle();
      if (!data) return NextResponse.json({ error: 'Not found' }, { status: 404 });
      if (data.expires_at && new Date(data.expires_at).getTime() < Date.now()) {
        return NextResponse.json({ error: 'Artifact expired' }, { status: 410 });
      }
      return NextResponse.json({ success: true, artifact: data });
    }

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    const { data: rows } = await supabase
      .from('parent_artifacts')
      .select('id, artifact_kind, title, share_token, generated_at, expires_at')
      .eq('user_id', user.id)
      .order('generated_at', { ascending: false })
      .limit(20);
    return NextResponse.json({ success: true, artifacts: rows || [] });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const supabase: any = await createServerClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const kind = body.kind || 'session_summary';

    // Pull what we need to compose the digest.
    const [{ data: streak }, { data: profile }, { data: recentEvals }, { data: masteries }] = await Promise.all([
      supabase.from('streaks').select('*').eq('user_id', user.id).maybeSingle(),
      supabase.from('profiles').select('full_name, current_class, board_code').eq('id', user.id).maybeSingle(),
      supabase.from('session_evaluations').select('score, evaluated_at, topic_id, subject_id').eq('user_id', user.id).order('evaluated_at', { ascending: false }).limit(10),
      supabase.from('mastery_scores').select('score, band, subject_slug').eq('user_id', user.id).order('updated_at', { ascending: false }).limit(20),
    ]);

    const name = profile?.full_name || 'your child';
    const classLabel = profile?.current_class ? `Class ${profile.current_class}` : '';
    const evals = recentEvals || [];
    const meanScore = evals.length > 0
      ? Math.round((evals.reduce((s: number, r: any) => s + (r.score || 0), 0) / evals.length) * 100)
      : null;

    let title = '';
    let body_md = '';
    if (kind === 'session_summary') {
      title = `${name}'s today — ${new Date().toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}`;
      const today = new Date().toISOString().split('T')[0];
      const todayEvals = evals.filter((e: any) => (e.evaluated_at || '').startsWith(today));
      body_md = [
        `# ${title}`,
        ``,
        `**Streak:** ${streak?.current_streak || 0} days · **Honesty XP:** ${streak?.honesty_xp || 0}`,
        ``,
        `**Today's exit-eval count:** ${todayEvals.length}`,
        meanScore !== null ? `**Average exit-eval score (last 10):** ${meanScore}%` : '',
        ``,
        `**Top mastery (recent):**`,
        ...(masteries || []).slice(0, 5).map((m: any) => `- ${m.subject_slug || 'subject'}: ${m.score}/100 · ${m.band}`),
        ``,
        `_Generated by MyCupIsEmpty. Honest measure — no overstating mastery, no hidden penalties._`,
      ].filter(Boolean).join('\n');
    } else if (kind === 'weekly_digest') {
      title = `${name}'s week — ending ${new Date().toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}`;
      body_md = [
        `# ${title}`,
        ``,
        `**Streak:** ${streak?.current_streak || 0} days (longest: ${streak?.longest_streak || 0})`,
        `**Honesty XP earned this week:** estimated from latest events`,
        ``,
        `**Avg exit-eval score:** ${meanScore !== null ? `${meanScore}%` : '—'} across ${evals.length} sessions`,
        ``,
        `**Subjects making progress:**`,
        ...(masteries || []).slice(0, 8).map((m: any) => `- ${m.subject_slug || 'subject'}: ${m.score}/100 · ${m.band}`),
        ``,
        `${classLabel ? `_${name} is in ${classLabel}._` : ''}`,
      ].filter(Boolean).join('\n');
    } else {
      title = `${name}'s month — ${new Date().toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}`;
      body_md = [
        `# ${title}`,
        ``,
        `Streak ${streak?.current_streak || 0} days · Honesty XP ${streak?.honesty_xp || 0}`,
        ``,
        `${meanScore !== null ? `Avg exit-eval score across recent sessions: **${meanScore}%**` : ''}`,
      ].filter(Boolean).join('\n');
    }

    const token = shareToken();
    const expiresAt = new Date(Date.now() + 30 * 86400 * 1000).toISOString();
    const { data: row } = await supabase.from('parent_artifacts').insert({
      user_id: user.id,
      artifact_kind: kind,
      title,
      body_md,
      pdf_url: null,
      share_token: token,
      language: 'en',
      expires_at: expiresAt,
    }).select().single();

    return NextResponse.json({ success: true, artifact: row });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
